-- MySQL Script generated by MySQL Workbench
-- 09/15/16 09:19:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banco_ADSI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_ADSI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_ADSI` DEFAULT CHARACTER SET utf8 ;
USE `banco_ADSI` ;

-- -----------------------------------------------------
-- Table `banco_ADSI`.`Documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_ADSI`.`Documento` (
  `documentoExtranjero` CHAR(15) NULL,
  `cedulaCiudadnia` CHAR(15) NULL,
  `targetaIdentidad` CHAR(15) NULL,
  `serialDocumento` VARCHAR(45) NULL,
  `Abogado_documento` CHAR(15) NOT NULL,
  PRIMARY KEY (`Abogado_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_ADSI`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_ADSI`.`Prestamo` (
  `NOMBRE_DOCUMENTO` VARCHAR(15) NOT NULL,
  `SOLICITANTE` CHAR(6) NULL,
  `FECHA_SALIDA` CHAR(6) NULL,
  `HORA` CHAR(6) NULL,
  `UBICACION` CHAR(8) NULL,
  `Documento_Abogado_documento` CHAR(15) NOT NULL,
  PRIMARY KEY (`NOMBRE_DOCUMENTO`, `Documento_Abogado_documento`),
  CONSTRAINT `fk_Prestamo_Documento1`
    FOREIGN KEY (`Documento_Abogado_documento`)
    REFERENCES `banco_ADSI`.`Documento` (`Abogado_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prestamo_Documento1_idx` ON `banco_ADSI`.`Prestamo` (`Documento_Abogado_documento` ASC);


-- -----------------------------------------------------
-- Table `banco_ADSI`.`servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_ADSI`.`servidor` (
  `idServidor` CHAR(15) NOT NULL,
  `almacenamiento` CHAR(15) NULL,
  PRIMARY KEY (`idServidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_ADSI`.`Archivista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_ADSI`.`Archivista` (
  `idArchivista` CHAR(15) NOT NULL,
  `nombreCompleto` CHAR(30) NULL,
  `correo` CHAR(45) NULL,
  `servidor_idServidor` CHAR(15) NOT NULL,
  PRIMARY KEY (`idArchivista`, `servidor_idServidor`),
  CONSTRAINT `fk_Archivista_servidor1`
    FOREIGN KEY (`servidor_idServidor`)
    REFERENCES `banco_ADSI`.`servidor` (`idServidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Archivista_servidor1_idx` ON `banco_ADSI`.`Archivista` (`servidor_idServidor` ASC);


-- -----------------------------------------------------
-- Table `banco_ADSI`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_ADSI`.`registro` (
  `documento` CHAR(15) NOT NULL,
  `direccion` CHAR(15) NULL,
  `telefono` CHAR(15) NULL,
  `contraseña` CHAR(15) NOT NULL,
  `nombreCompleto` CHAR(35) NOT NULL,
  `Archivista_documento` CHAR(15) NOT NULL,
  `servidor_idServidor` CHAR(15) NOT NULL,
  PRIMARY KEY (`documento`, `Archivista_documento`, `servidor_idServidor`),
  CONSTRAINT `fk_registro_Archivista1`
    FOREIGN KEY (`Archivista_documento`)
    REFERENCES `banco_ADSI`.`Archivista` (`idArchivista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_servidor1`
    FOREIGN KEY (`servidor_idServidor`)
    REFERENCES `banco_ADSI`.`servidor` (`idServidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_registro_Archivista1_idx` ON `banco_ADSI`.`registro` (`Archivista_documento` ASC);

CREATE INDEX `fk_registro_servidor1_idx` ON `banco_ADSI`.`registro` (`servidor_idServidor` ASC);


-- -----------------------------------------------------
-- Table `banco_ADSI`.`Abogado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_ADSI`.`Abogado` (
  `documento` CHAR(15) NOT NULL,
  `nombreCompleto` CHAR(35) NULL,
  `correo` VARCHAR(45) NULL,
  `registro_documento` CHAR(15) NOT NULL,
  `Prestamo_NOMBRE_DOCUMENTO` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`documento`, `registro_documento`, `Prestamo_NOMBRE_DOCUMENTO`),
  CONSTRAINT `fk_Abogado_registro1`
    FOREIGN KEY (`registro_documento`)
    REFERENCES `banco_ADSI`.`registro` (`documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Abogado_Prestamo1`
    FOREIGN KEY (`Prestamo_NOMBRE_DOCUMENTO`)
    REFERENCES `banco_ADSI`.`Prestamo` (`NOMBRE_DOCUMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Abogado_registro1_idx` ON `banco_ADSI`.`Abogado` (`registro_documento` ASC);

CREATE INDEX `fk_Abogado_Prestamo1_idx` ON `banco_ADSI`.`Abogado` (`Prestamo_NOMBRE_DOCUMENTO` ASC);


-- -----------------------------------------------------
-- Table `banco_ADSI`.`Archivo_Guardado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_ADSI`.`Archivo_Guardado` (
  `CODIGO` CHAR(10) NOT NULL,
  ` HISTORIAL` CHAR(10) NULL,
  ` FECHA` CHAR(15) NULL,
  `servidor_idServidor` CHAR(15) NOT NULL,
  `Documento_Abogado_documento` CHAR(15) NOT NULL,
  PRIMARY KEY (`CODIGO`, `servidor_idServidor`, `Documento_Abogado_documento`),
  CONSTRAINT `fk_Archivo_Guardado_servidor1`
    FOREIGN KEY (`servidor_idServidor`)
    REFERENCES `banco_ADSI`.`servidor` (`idServidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Archivo_Guardado_Documento1`
    FOREIGN KEY (`Documento_Abogado_documento`)
    REFERENCES `banco_ADSI`.`Documento` (`Abogado_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Archivo_Guardado_servidor1_idx` ON `banco_ADSI`.`Archivo_Guardado` (`servidor_idServidor` ASC);

CREATE INDEX `fk_Archivo_Guardado_Documento1_idx` ON `banco_ADSI`.`Archivo_Guardado` (`Documento_Abogado_documento` ASC);


-- -----------------------------------------------------
-- Table `banco_ADSI`.`peticion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_ADSI`.`peticion` (
  `idpeticion` INT NOT NULL,
  PRIMARY KEY (`idpeticion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
